# Generated by Django 4.1.4 on 2022-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0002_distractor_model_paragraph_document_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
