# Generated by Django 4.1.4 on 2023-01-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="creation_date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
