# Generated by Django 4.1.4 on 2022-12-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0003_model_comment_alter_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distractor",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distractors",
                to="aqg.model",
            ),
        ),
        migrations.AlterField(
            model_name="distractor",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distractors",
                to="aqg.question",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="aqg.question",
            ),
        ),
    ]
