# Generated by Django 4.1.4 on 2023-01-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0003_alter_model_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="english_false_answers",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="english_selfestimation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="english_validation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_student",
        ),
    ]
