# Generated by Django 4.1.4 on 2023-01-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0004_remove_profile_english_false_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="paragraph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="aqg.paragraph",
            ),
        ),
    ]
