# Generated by Django 4.1.4 on 2023-01-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0006_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paragraphs",
                to="aqg.dataset",
            ),
        ),
    ]
