# Generated by Django 4.1.4 on 2023-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0008_rename_model_paragraph_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("max_eval_per_question", models.IntegerField(default=5)),
                ("max_questions_per_subject", models.IntegerField(default=20)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="additional_questions",
            field=models.IntegerField(default=0),
        ),
    ]
