# Generated by Django 4.1.4 on 2022-12-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aqg", "0008_evaluation_familiarity_model_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="english_selfestimation",
            field=models.IntegerField(default=0),
        ),
    ]
