# Generated by Django 4.1.4 on 2023-01-06 12:16

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", userauth.models.CustomManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=80, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
