# Generated by Django 4.1.4 on 2023-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_url",
            field=models.URLField(
                default="https://la.ait.kyushu-u.ac.jp/qu/aqg/login/"
            ),
        ),
    ]
